In [1]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf
import sklearn.model_selection
from tensorflow import keras
from tensorflow.keras import layers

import numpy as np
import pandas as pd

In [2]:
dataset_path = 'Admission_Predict_Ver1.1.csv'
raw_dataset = pd.read_csv(dataset_path, sep=",")

raw_dataset.info()
raw_dataset.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
Serial No.           500 non-null int64
GRE Score            500 non-null int64
TOEFL Score          500 non-null int64
University Rating    500 non-null int64
SOP                  500 non-null float64
LOR                  500 non-null float64
CGPA                 500 non-null float64
Research             500 non-null int64
Chance of Admit      500 non-null float64
dtypes: float64(4), int64(5)
memory usage: 35.2 KB


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

---
# Regresión

In [3]:
dataset = raw_dataset.copy()

x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values.reshape(-1, 1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, shuffle=True, random_state=0)

In [4]:
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 120.  ,   5.  , ...,   5.  ,   9.56,   1.  ],
       [312.  , 103.  ,   4.  , ...,   5.  ,   8.43,   0.  ],
       [327.  , 113.  ,   4.  , ...,   4.5 ,   9.04,   0.  ]])

In [5]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [6]:
def build_model():   
    model = keras.models.Sequential()
    model.add(keras.layers.Dense(32, activation = 'relu', input_shape = (x_train.shape[1],)))
    model.add(keras.layers.Dense(1, activation = 'sigmoid'))
    model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['acc'])
    
    return model

In [7]:
model = build_model()
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                256       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


In [8]:
history = model.fit(x_train, y_train, 
                    epochs=40,
                    validation_data=(x_test, y_test))

Train on 335 samples, validate on 165 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/40
335/335 [==============================] - 0s 620us/sample - loss: 1.5429 - acc: 0.0000e+00 - val_loss: 0.6818 - val_acc: 0.0000e+00
Epoch 2/40
335/335 [==============================] - 0s 67us/sample - loss: 0.9442 - acc: 0.0000e+00 - val_loss: 0.8856 - val_acc: 0.0000e+00
Epoch 3/40
335/335 [==============================] - 0s 61us/sample - loss: 0.8550 - acc: 0.0000e+00 - val_loss: 1.0607 - val_acc: 0.0000e+00
Epoch 4/40
335/335 [==============================] - 0s 72us/sample - loss: 0.9237 - acc: 0.0000e+00 - val_loss: 0.9291 - val_acc: 0.0000e+00
Epoch 5/40
335/335 [==============================] - 0s 75us/sample - loss: 1.0041 - acc: 0.0000e+00 - val_loss: 0.6577 - val_acc: 0.0000e+00
Epoch 6/40
335/335 [==============================] - 0s 93us/sample - loss: 0.8137 - acc: 0.0000e+00 - val_loss: 0.9253 - val_acc: 0.0000e+00
Epoch 7/40
335/335 [===========================

In [23]:
predictions = model.predict(x_test)

In [24]:
predictions

array([[0.78375304],
       [0.5576973 ],
       [0.40692708],
       [0.6430629 ],
       [0.40216345],
       [0.49061665],
       [0.2527734 ],
       [0.56417227],
       [0.320105  ],
       [0.5884094 ],
       [0.4254623 ],
       [0.5666375 ],
       [0.40156654],
       [0.5718009 ],
       [0.54402244],
       [0.4321174 ],
       [0.7185479 ],
       [0.4062782 ],
       [0.5040413 ],
       [0.19774789],
       [0.4688293 ],
       [0.7563018 ],
       [0.49964875],
       [0.72360766],
       [0.7215414 ],
       [0.5714142 ],
       [0.22165042],
       [0.3711159 ],
       [0.5785028 ],
       [0.53820556],
       [0.5537397 ],
       [0.57174855],
       [0.26568896],
       [0.66487753],
       [0.33426654],
       [0.5180821 ],
       [0.7695986 ],
       [0.7090063 ],
       [0.48496673],
       [0.35928488],
       [0.48521253],
       [0.62381   ],
       [0.54122484],
       [0.51926965],
       [0.4790588 ],
       [0.73977554],
       [0.65708965],
       [0.552

In [36]:
# Error cuadratico medio
from sklearn.metrics import mean_squared_error
cm = mean_squared_error(y_test, predictions)
cm

0.04915168092436579

---
# Clasificación

In [ ]:
# Hacer una red con 5 salidas y ver cual se prende???

In [25]:
def classify_predictions(predictions):
    arr = []
    for pred in predictions:
        pred = pred[0]
        if 0.9 < pred < 1:
            pred_class = "Very Good"
        if 0.8 < pred < 0.9:
            pred_class = "Good"
        if 0.65 < pred < 0.8:
            pred_class = "Medium"
        if 0.5 < pred < 0.65:
            pred_class = "Bad"
        if 0 < pred < 0.5:
            pred_class = "Very Bad"

        arr.append([pred_class])


    return np.array(arr)

classified_predictions = classify_predictions(predictions)
classified_y_test = classify_predictions(y_test)
classified_predictions, classified_y_test

(array([['Medium'],
        ['Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Very Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Medium'],
        ['Very Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Very Bad'],
        ['Medium'],
        ['Very Bad'],
        ['Medium'],
        ['Medium'],
        ['Bad'],
        ['Very Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Bad'],
        ['Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Medium'],
        ['Very Bad'],
        ['Bad'],
        ['Medium'],
        ['Medium'],
        ['Very Bad'],
        ['Very Bad'],
        ['Very Bad'],
        ['Bad'],
        ['Bad'],
        ['Bad'],
        ['Very Bad'],
        ['Medium'],
        ['Medium'],
        ['Bad'],
        ['Very Bad'],
        ['Medium'],
        ['Ve

In [37]:
# % de casos de éxito 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(classified_y_test, classified_predictions)
print('Evaluated accuracy: ', (accuracy * 100))

Evaluated accuracy:  15.757575757575756
